/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: binfmt-misc.proto */

#ifndef PROTOBUF_C_binfmt_2dmisc_2eproto__INCLUDED
#define PROTOBUF_C_binfmt_2dmisc_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _BinfmtMiscEntry BinfmtMiscEntry;


/* --- enums --- */


/* --- messages --- */

struct  _BinfmtMiscEntry
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean enabled;
  char *interpreter;
  char *flags;
  char *extension;
  char *magic;
  char *mask;
  protobuf_c_boolean has_offset;
  int32_t offset;
};
#define BINFMT_MISC_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&binfmt_misc_entry__descriptor) \
    , NULL, 0, NULL, NULL, NULL, NULL, NULL, 0,0 }


/* BinfmtMiscEntry methods */
void   binfmt_misc_entry__init
                     (BinfmtMiscEntry         *message);
size_t binfmt_misc_entry__get_packed_size
                     (const BinfmtMiscEntry   *message);
size_t binfmt_misc_entry__pack
                     (const BinfmtMiscEntry   *message,
                      uint8_t             *out);
size_t binfmt_misc_entry__pack_to_buffer
                     (const BinfmtMiscEntry   *message,
                      ProtobufCBuffer     *buffer);
BinfmtMiscEntry *
       binfmt_misc_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   binfmt_misc_entry__free_unpacked
                     (BinfmtMiscEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BinfmtMiscEntry_Closure)
                 (const BinfmtMiscEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor binfmt_misc_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_binfmt_2dmisc_2eproto__INCLUDED */
