/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: core-aarch64.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "core-aarch64.pb-c.h"
void   user_aarch64_regs_entry__init
                     (UserAarch64RegsEntry         *message)
{
  static UserAarch64RegsEntry init_value = USER_AARCH64_REGS_ENTRY__INIT;
  *message = init_value;
}
size_t user_aarch64_regs_entry__get_packed_size
                     (const UserAarch64RegsEntry *message)
{
  assert(message->base.descriptor == &user_aarch64_regs_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_aarch64_regs_entry__pack
                     (const UserAarch64RegsEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user_aarch64_regs_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_aarch64_regs_entry__pack_to_buffer
                     (const UserAarch64RegsEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user_aarch64_regs_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserAarch64RegsEntry *
       user_aarch64_regs_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserAarch64RegsEntry *)
     protobuf_c_message_unpack (&user_aarch64_regs_entry__descriptor,
                                allocator, len, data);
}
void   user_aarch64_regs_entry__free_unpacked
                     (UserAarch64RegsEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &user_aarch64_regs_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   user_aarch64_fpsimd_context_entry__init
                     (UserAarch64FpsimdContextEntry         *message)
{
  static UserAarch64FpsimdContextEntry init_value = USER_AARCH64_FPSIMD_CONTEXT_ENTRY__INIT;
  *message = init_value;
}
size_t user_aarch64_fpsimd_context_entry__get_packed_size
                     (const UserAarch64FpsimdContextEntry *message)
{
  assert(message->base.descriptor == &user_aarch64_fpsimd_context_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_aarch64_fpsimd_context_entry__pack
                     (const UserAarch64FpsimdContextEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user_aarch64_fpsimd_context_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_aarch64_fpsimd_context_entry__pack_to_buffer
                     (const UserAarch64FpsimdContextEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user_aarch64_fpsimd_context_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserAarch64FpsimdContextEntry *
       user_aarch64_fpsimd_context_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserAarch64FpsimdContextEntry *)
     protobuf_c_message_unpack (&user_aarch64_fpsimd_context_entry__descriptor,
                                allocator, len, data);
}
void   user_aarch64_fpsimd_context_entry__free_unpacked
                     (UserAarch64FpsimdContextEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &user_aarch64_fpsimd_context_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   thread_info_aarch64__init
                     (ThreadInfoAarch64         *message)
{
  static ThreadInfoAarch64 init_value = THREAD_INFO_AARCH64__INIT;
  *message = init_value;
}
size_t thread_info_aarch64__get_packed_size
                     (const ThreadInfoAarch64 *message)
{
  assert(message->base.descriptor == &thread_info_aarch64__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t thread_info_aarch64__pack
                     (const ThreadInfoAarch64 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_info_aarch64__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t thread_info_aarch64__pack_to_buffer
                     (const ThreadInfoAarch64 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &thread_info_aarch64__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ThreadInfoAarch64 *
       thread_info_aarch64__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ThreadInfoAarch64 *)
     protobuf_c_message_unpack (&thread_info_aarch64__descriptor,
                                allocator, len, data);
}
void   thread_info_aarch64__free_unpacked
                     (ThreadInfoAarch64 *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &thread_info_aarch64__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor user_aarch64_regs_entry__field_descriptors[4] =
{
  {
    "regs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(UserAarch64RegsEntry, n_regs),
    offsetof(UserAarch64RegsEntry, regs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UserAarch64RegsEntry, sp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UserAarch64RegsEntry, pc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pstate",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UserAarch64RegsEntry, pstate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_aarch64_regs_entry__field_indices_by_name[] = {
  2,   /* field[2] = pc */
  3,   /* field[3] = pstate */
  0,   /* field[0] = regs */
  1,   /* field[1] = sp */
};
static const ProtobufCIntRange user_aarch64_regs_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor user_aarch64_regs_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "user_aarch64_regs_entry",
  "UserAarch64RegsEntry",
  "UserAarch64RegsEntry",
  "",
  sizeof(UserAarch64RegsEntry),
  4,
  user_aarch64_regs_entry__field_descriptors,
  user_aarch64_regs_entry__field_indices_by_name,
  1,  user_aarch64_regs_entry__number_ranges,
  (ProtobufCMessageInit) user_aarch64_regs_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor user_aarch64_fpsimd_context_entry__field_descriptors[3] =
{
  {
    "vregs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(UserAarch64FpsimdContextEntry, n_vregs),
    offsetof(UserAarch64FpsimdContextEntry, vregs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpsr",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserAarch64FpsimdContextEntry, fpsr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpcr",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserAarch64FpsimdContextEntry, fpcr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_aarch64_fpsimd_context_entry__field_indices_by_name[] = {
  2,   /* field[2] = fpcr */
  1,   /* field[1] = fpsr */
  0,   /* field[0] = vregs */
};
static const ProtobufCIntRange user_aarch64_fpsimd_context_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor user_aarch64_fpsimd_context_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "user_aarch64_fpsimd_context_entry",
  "UserAarch64FpsimdContextEntry",
  "UserAarch64FpsimdContextEntry",
  "",
  sizeof(UserAarch64FpsimdContextEntry),
  3,
  user_aarch64_fpsimd_context_entry__field_descriptors,
  user_aarch64_fpsimd_context_entry__field_indices_by_name,
  1,  user_aarch64_fpsimd_context_entry__number_ranges,
  (ProtobufCMessageInit) user_aarch64_fpsimd_context_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_info_aarch64__field_descriptors[4] =
{
  {
    "clear_tid_addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ThreadInfoAarch64, clear_tid_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tls",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ThreadInfoAarch64, tls),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpregs",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ThreadInfoAarch64, gpregs),
    &user_aarch64_regs_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpsimd",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ThreadInfoAarch64, fpsimd),
    &user_aarch64_fpsimd_context_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned thread_info_aarch64__field_indices_by_name[] = {
  0,   /* field[0] = clear_tid_addr */
  3,   /* field[3] = fpsimd */
  2,   /* field[2] = gpregs */
  1,   /* field[1] = tls */
};
static const ProtobufCIntRange thread_info_aarch64__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor thread_info_aarch64__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "thread_info_aarch64",
  "ThreadInfoAarch64",
  "ThreadInfoAarch64",
  "",
  sizeof(ThreadInfoAarch64),
  4,
  thread_info_aarch64__field_descriptors,
  thread_info_aarch64__field_indices_by_name,
  1,  thread_info_aarch64__number_ranges,
  (ProtobufCMessageInit) thread_info_aarch64__init,
  NULL,NULL,NULL    /* reserved[123] */
};
