/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: core-arm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "core-arm.pb-c.h"
void   user_arm_regs_entry__init
                     (UserArmRegsEntry         *message)
{
  static UserArmRegsEntry init_value = USER_ARM_REGS_ENTRY__INIT;
  *message = init_value;
}
size_t user_arm_regs_entry__get_packed_size
                     (const UserArmRegsEntry *message)
{
  assert(message->base.descriptor == &user_arm_regs_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_arm_regs_entry__pack
                     (const UserArmRegsEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user_arm_regs_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_arm_regs_entry__pack_to_buffer
                     (const UserArmRegsEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user_arm_regs_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserArmRegsEntry *
       user_arm_regs_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserArmRegsEntry *)
     protobuf_c_message_unpack (&user_arm_regs_entry__descriptor,
                                allocator, len, data);
}
void   user_arm_regs_entry__free_unpacked
                     (UserArmRegsEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &user_arm_regs_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   user_arm_vfpstate_entry__init
                     (UserArmVfpstateEntry         *message)
{
  static UserArmVfpstateEntry init_value = USER_ARM_VFPSTATE_ENTRY__INIT;
  *message = init_value;
}
size_t user_arm_vfpstate_entry__get_packed_size
                     (const UserArmVfpstateEntry *message)
{
  assert(message->base.descriptor == &user_arm_vfpstate_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_arm_vfpstate_entry__pack
                     (const UserArmVfpstateEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user_arm_vfpstate_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_arm_vfpstate_entry__pack_to_buffer
                     (const UserArmVfpstateEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user_arm_vfpstate_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserArmVfpstateEntry *
       user_arm_vfpstate_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserArmVfpstateEntry *)
     protobuf_c_message_unpack (&user_arm_vfpstate_entry__descriptor,
                                allocator, len, data);
}
void   user_arm_vfpstate_entry__free_unpacked
                     (UserArmVfpstateEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &user_arm_vfpstate_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   thread_info_arm__init
                     (ThreadInfoArm         *message)
{
  static ThreadInfoArm init_value = THREAD_INFO_ARM__INIT;
  *message = init_value;
}
size_t thread_info_arm__get_packed_size
                     (const ThreadInfoArm *message)
{
  assert(message->base.descriptor == &thread_info_arm__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t thread_info_arm__pack
                     (const ThreadInfoArm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_info_arm__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t thread_info_arm__pack_to_buffer
                     (const ThreadInfoArm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &thread_info_arm__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ThreadInfoArm *
       thread_info_arm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ThreadInfoArm *)
     protobuf_c_message_unpack (&thread_info_arm__descriptor,
                                allocator, len, data);
}
void   thread_info_arm__free_unpacked
                     (ThreadInfoArm *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &thread_info_arm__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor user_arm_regs_entry__field_descriptors[18] =
{
  {
    "r0",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r2",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r3",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r4",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r5",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r6",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r7",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r7),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r8",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r8),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r9",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r9),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r10",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, r10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fp",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, fp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sp",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, sp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lr",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, lr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, pc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpsr",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, cpsr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orig_r0",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmRegsEntry, orig_r0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_arm_regs_entry__field_indices_by_name[] = {
  16,   /* field[16] = cpsr */
  11,   /* field[11] = fp */
  12,   /* field[12] = ip */
  14,   /* field[14] = lr */
  17,   /* field[17] = orig_r0 */
  15,   /* field[15] = pc */
  0,   /* field[0] = r0 */
  1,   /* field[1] = r1 */
  10,   /* field[10] = r10 */
  2,   /* field[2] = r2 */
  3,   /* field[3] = r3 */
  4,   /* field[4] = r4 */
  5,   /* field[5] = r5 */
  6,   /* field[6] = r6 */
  7,   /* field[7] = r7 */
  8,   /* field[8] = r8 */
  9,   /* field[9] = r9 */
  13,   /* field[13] = sp */
};
static const ProtobufCIntRange user_arm_regs_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor user_arm_regs_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "user_arm_regs_entry",
  "UserArmRegsEntry",
  "UserArmRegsEntry",
  "",
  sizeof(UserArmRegsEntry),
  18,
  user_arm_regs_entry__field_descriptors,
  user_arm_regs_entry__field_indices_by_name,
  1,  user_arm_regs_entry__number_ranges,
  (ProtobufCMessageInit) user_arm_regs_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor user_arm_vfpstate_entry__field_descriptors[5] =
{
  {
    "vfp_regs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(UserArmVfpstateEntry, n_vfp_regs),
    offsetof(UserArmVfpstateEntry, vfp_regs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpscr",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmVfpstateEntry, fpscr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpexc",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmVfpstateEntry, fpexc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpinst",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmVfpstateEntry, fpinst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpinst2",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UserArmVfpstateEntry, fpinst2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_arm_vfpstate_entry__field_indices_by_name[] = {
  2,   /* field[2] = fpexc */
  3,   /* field[3] = fpinst */
  4,   /* field[4] = fpinst2 */
  1,   /* field[1] = fpscr */
  0,   /* field[0] = vfp_regs */
};
static const ProtobufCIntRange user_arm_vfpstate_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor user_arm_vfpstate_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "user_arm_vfpstate_entry",
  "UserArmVfpstateEntry",
  "UserArmVfpstateEntry",
  "",
  sizeof(UserArmVfpstateEntry),
  5,
  user_arm_vfpstate_entry__field_descriptors,
  user_arm_vfpstate_entry__field_indices_by_name,
  1,  user_arm_vfpstate_entry__number_ranges,
  (ProtobufCMessageInit) user_arm_vfpstate_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_info_arm__field_descriptors[4] =
{
  {
    "clear_tid_addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ThreadInfoArm, clear_tid_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tls",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ThreadInfoArm, tls),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpregs",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ThreadInfoArm, gpregs),
    &user_arm_regs_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpstate",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ThreadInfoArm, fpstate),
    &user_arm_vfpstate_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned thread_info_arm__field_indices_by_name[] = {
  0,   /* field[0] = clear_tid_addr */
  3,   /* field[3] = fpstate */
  2,   /* field[2] = gpregs */
  1,   /* field[1] = tls */
};
static const ProtobufCIntRange thread_info_arm__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor thread_info_arm__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "thread_info_arm",
  "ThreadInfoArm",
  "ThreadInfoArm",
  "",
  sizeof(ThreadInfoArm),
  4,
  thread_info_arm__field_descriptors,
  thread_info_arm__field_indices_by_name,
  1,  thread_info_arm__number_ranges,
  (ProtobufCMessageInit) thread_info_arm__init,
  NULL,NULL,NULL    /* reserved[123] */
};
