/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: creds.proto */

#ifndef PROTOBUF_C_creds_2eproto__INCLUDED
#define PROTOBUF_C_creds_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CredsEntry CredsEntry;


/* --- enums --- */


/* --- messages --- */

struct  _CredsEntry
{
  ProtobufCMessage base;
  uint32_t uid;
  uint32_t gid;
  uint32_t euid;
  uint32_t egid;
  uint32_t suid;
  uint32_t sgid;
  uint32_t fsuid;
  uint32_t fsgid;
  size_t n_cap_inh;
  uint32_t *cap_inh;
  size_t n_cap_prm;
  uint32_t *cap_prm;
  size_t n_cap_eff;
  uint32_t *cap_eff;
  size_t n_cap_bnd;
  uint32_t *cap_bnd;
  uint32_t secbits;
  size_t n_groups;
  uint32_t *groups;
  char *lsm_profile;
  char *lsm_sockcreate;
};
#define CREDS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&creds_entry__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0, 0,NULL, NULL, NULL }


/* CredsEntry methods */
void   creds_entry__init
                     (CredsEntry         *message);
size_t creds_entry__get_packed_size
                     (const CredsEntry   *message);
size_t creds_entry__pack
                     (const CredsEntry   *message,
                      uint8_t             *out);
size_t creds_entry__pack_to_buffer
                     (const CredsEntry   *message,
                      ProtobufCBuffer     *buffer);
CredsEntry *
       creds_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   creds_entry__free_unpacked
                     (CredsEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CredsEntry_Closure)
                 (const CredsEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor creds_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_creds_2eproto__INCLUDED */
