/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: eventpoll.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "eventpoll.pb-c.h"
void   eventpoll_tfd_entry__init
                     (EventpollTfdEntry         *message)
{
  static EventpollTfdEntry init_value = EVENTPOLL_TFD_ENTRY__INIT;
  *message = init_value;
}
size_t eventpoll_tfd_entry__get_packed_size
                     (const EventpollTfdEntry *message)
{
  assert(message->base.descriptor == &eventpoll_tfd_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eventpoll_tfd_entry__pack
                     (const EventpollTfdEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eventpoll_tfd_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eventpoll_tfd_entry__pack_to_buffer
                     (const EventpollTfdEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eventpoll_tfd_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EventpollTfdEntry *
       eventpoll_tfd_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EventpollTfdEntry *)
     protobuf_c_message_unpack (&eventpoll_tfd_entry__descriptor,
                                allocator, len, data);
}
void   eventpoll_tfd_entry__free_unpacked
                     (EventpollTfdEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &eventpoll_tfd_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eventpoll_file_entry__init
                     (EventpollFileEntry         *message)
{
  static EventpollFileEntry init_value = EVENTPOLL_FILE_ENTRY__INIT;
  *message = init_value;
}
size_t eventpoll_file_entry__get_packed_size
                     (const EventpollFileEntry *message)
{
  assert(message->base.descriptor == &eventpoll_file_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eventpoll_file_entry__pack
                     (const EventpollFileEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eventpoll_file_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eventpoll_file_entry__pack_to_buffer
                     (const EventpollFileEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eventpoll_file_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EventpollFileEntry *
       eventpoll_file_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EventpollFileEntry *)
     protobuf_c_message_unpack (&eventpoll_file_entry__descriptor,
                                allocator, len, data);
}
void   eventpoll_file_entry__free_unpacked
                     (EventpollFileEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &eventpoll_file_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor eventpoll_tfd_entry__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EventpollTfdEntry, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tfd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EventpollTfdEntry, tfd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EventpollTfdEntry, events),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(EventpollTfdEntry, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dev",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EventpollTfdEntry, has_dev),
    offsetof(EventpollTfdEntry, dev),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inode",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(EventpollTfdEntry, has_inode),
    offsetof(EventpollTfdEntry, inode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(EventpollTfdEntry, has_pos),
    offsetof(EventpollTfdEntry, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eventpoll_tfd_entry__field_indices_by_name[] = {
  3,   /* field[3] = data */
  4,   /* field[4] = dev */
  2,   /* field[2] = events */
  0,   /* field[0] = id */
  5,   /* field[5] = inode */
  6,   /* field[6] = pos */
  1,   /* field[1] = tfd */
};
static const ProtobufCIntRange eventpoll_tfd_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor eventpoll_tfd_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "eventpoll_tfd_entry",
  "EventpollTfdEntry",
  "EventpollTfdEntry",
  "",
  sizeof(EventpollTfdEntry),
  7,
  eventpoll_tfd_entry__field_descriptors,
  eventpoll_tfd_entry__field_indices_by_name,
  1,  eventpoll_tfd_entry__number_ranges,
  (ProtobufCMessageInit) eventpoll_tfd_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eventpoll_file_entry__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EventpollFileEntry, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(EventpollFileEntry, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fown",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EventpollFileEntry, fown),
    &fown_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tfd",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventpollFileEntry, n_tfd),
    offsetof(EventpollFileEntry, tfd),
    &eventpoll_tfd_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eventpoll_file_entry__field_indices_by_name[] = {
  1,   /* field[1] = flags */
  2,   /* field[2] = fown */
  0,   /* field[0] = id */
  3,   /* field[3] = tfd */
};
static const ProtobufCIntRange eventpoll_file_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor eventpoll_file_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "eventpoll_file_entry",
  "EventpollFileEntry",
  "EventpollFileEntry",
  "",
  sizeof(EventpollFileEntry),
  4,
  eventpoll_file_entry__field_descriptors,
  eventpoll_file_entry__field_indices_by_name,
  1,  eventpoll_file_entry__number_ranges,
  (ProtobufCMessageInit) eventpoll_file_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
