/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ext-file.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ext-file.pb-c.h"
void   ext_file_entry__init
                     (ExtFileEntry         *message)
{
  static ExtFileEntry init_value = EXT_FILE_ENTRY__INIT;
  *message = init_value;
}
size_t ext_file_entry__get_packed_size
                     (const ExtFileEntry *message)
{
  assert(message->base.descriptor == &ext_file_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ext_file_entry__pack
                     (const ExtFileEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ext_file_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ext_file_entry__pack_to_buffer
                     (const ExtFileEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ext_file_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExtFileEntry *
       ext_file_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExtFileEntry *)
     protobuf_c_message_unpack (&ext_file_entry__descriptor,
                                allocator, len, data);
}
void   ext_file_entry__free_unpacked
                     (ExtFileEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ext_file_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ext_file_entry__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ExtFileEntry, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fown",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ExtFileEntry, fown),
    &fown_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ext_file_entry__field_indices_by_name[] = {
  1,   /* field[1] = fown */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange ext_file_entry__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ext_file_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ext_file_entry",
  "ExtFileEntry",
  "ExtFileEntry",
  "",
  sizeof(ExtFileEntry),
  2,
  ext_file_entry__field_descriptors,
  ext_file_entry__field_indices_by_name,
  2,  ext_file_entry__number_ranges,
  (ProtobufCMessageInit) ext_file_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
