/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ipc-msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ipc-msg.pb-c.h"
void   ipc_msg__init
                     (IpcMsg         *message)
{
  static IpcMsg init_value = IPC_MSG__INIT;
  *message = init_value;
}
size_t ipc_msg__get_packed_size
                     (const IpcMsg *message)
{
  assert(message->base.descriptor == &ipc_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc_msg__pack
                     (const IpcMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc_msg__pack_to_buffer
                     (const IpcMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IpcMsg *
       ipc_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IpcMsg *)
     protobuf_c_message_unpack (&ipc_msg__descriptor,
                                allocator, len, data);
}
void   ipc_msg__free_unpacked
                     (IpcMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc_msg_entry__init
                     (IpcMsgEntry         *message)
{
  static IpcMsgEntry init_value = IPC_MSG_ENTRY__INIT;
  *message = init_value;
}
size_t ipc_msg_entry__get_packed_size
                     (const IpcMsgEntry *message)
{
  assert(message->base.descriptor == &ipc_msg_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc_msg_entry__pack
                     (const IpcMsgEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc_msg_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc_msg_entry__pack_to_buffer
                     (const IpcMsgEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc_msg_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IpcMsgEntry *
       ipc_msg_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IpcMsgEntry *)
     protobuf_c_message_unpack (&ipc_msg_entry__descriptor,
                                allocator, len, data);
}
void   ipc_msg_entry__free_unpacked
                     (IpcMsgEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc_msg_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ipc_msg__field_descriptors[2] =
{
  {
    "mtype",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(IpcMsg, mtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msize",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcMsg, msize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc_msg__field_indices_by_name[] = {
  1,   /* field[1] = msize */
  0,   /* field[0] = mtype */
};
static const ProtobufCIntRange ipc_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ipc_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc_msg",
  "IpcMsg",
  "IpcMsg",
  "",
  sizeof(IpcMsg),
  2,
  ipc_msg__field_descriptors,
  ipc_msg__field_indices_by_name,
  1,  ipc_msg__number_ranges,
  (ProtobufCMessageInit) ipc_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc_msg_entry__field_descriptors[3] =
{
  {
    "desc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(IpcMsgEntry, desc),
    &ipc_desc_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qbytes",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcMsgEntry, qbytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qnum",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcMsgEntry, qnum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc_msg_entry__field_indices_by_name[] = {
  0,   /* field[0] = desc */
  1,   /* field[1] = qbytes */
  2,   /* field[2] = qnum */
};
static const ProtobufCIntRange ipc_msg_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ipc_msg_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc_msg_entry",
  "IpcMsgEntry",
  "IpcMsgEntry",
  "",
  sizeof(IpcMsgEntry),
  3,
  ipc_msg_entry__field_descriptors,
  ipc_msg_entry__field_indices_by_name,
  1,  ipc_msg_entry__number_ranges,
  (ProtobufCMessageInit) ipc_msg_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
