/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ipc-desc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ipc-desc.pb-c.h"
void   ipc_desc_entry__init
                     (IpcDescEntry         *message)
{
  static IpcDescEntry init_value = IPC_DESC_ENTRY__INIT;
  *message = init_value;
}
size_t ipc_desc_entry__get_packed_size
                     (const IpcDescEntry *message)
{
  assert(message->base.descriptor == &ipc_desc_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc_desc_entry__pack
                     (const IpcDescEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc_desc_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc_desc_entry__pack_to_buffer
                     (const IpcDescEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc_desc_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IpcDescEntry *
       ipc_desc_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IpcDescEntry *)
     protobuf_c_message_unpack (&ipc_desc_entry__descriptor,
                                allocator, len, data);
}
void   ipc_desc_entry__free_unpacked
                     (IpcDescEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc_desc_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ipc_desc_entry__field_descriptors[7] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcDescEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcDescEntry, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcDescEntry, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cuid",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcDescEntry, cuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cgid",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcDescEntry, cgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcDescEntry, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(IpcDescEntry, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc_desc_entry__field_indices_by_name[] = {
  4,   /* field[4] = cgid */
  3,   /* field[3] = cuid */
  2,   /* field[2] = gid */
  6,   /* field[6] = id */
  0,   /* field[0] = key */
  5,   /* field[5] = mode */
  1,   /* field[1] = uid */
};
static const ProtobufCIntRange ipc_desc_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ipc_desc_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc_desc_entry",
  "IpcDescEntry",
  "IpcDescEntry",
  "",
  sizeof(IpcDescEntry),
  7,
  ipc_desc_entry__field_descriptors,
  ipc_desc_entry__field_indices_by_name,
  1,  ipc_desc_entry__number_ranges,
  (ProtobufCMessageInit) ipc_desc_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
