/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mm.pb-c.h"
void   aio_ring_entry__init
                     (AioRingEntry         *message)
{
  static AioRingEntry init_value = AIO_RING_ENTRY__INIT;
  *message = init_value;
}
size_t aio_ring_entry__get_packed_size
                     (const AioRingEntry *message)
{
  assert(message->base.descriptor == &aio_ring_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aio_ring_entry__pack
                     (const AioRingEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aio_ring_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aio_ring_entry__pack_to_buffer
                     (const AioRingEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aio_ring_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AioRingEntry *
       aio_ring_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AioRingEntry *)
     protobuf_c_message_unpack (&aio_ring_entry__descriptor,
                                allocator, len, data);
}
void   aio_ring_entry__free_unpacked
                     (AioRingEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &aio_ring_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mm_entry__init
                     (MmEntry         *message)
{
  static MmEntry init_value = MM_ENTRY__INIT;
  *message = init_value;
}
size_t mm_entry__get_packed_size
                     (const MmEntry *message)
{
  assert(message->base.descriptor == &mm_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mm_entry__pack
                     (const MmEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mm_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mm_entry__pack_to_buffer
                     (const MmEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mm_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MmEntry *
       mm_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MmEntry *)
     protobuf_c_message_unpack (&mm_entry__descriptor,
                                allocator, len, data);
}
void   mm_entry__free_unpacked
                     (MmEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mm_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor aio_ring_entry__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(AioRingEntry, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nr_req",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AioRingEntry, nr_req),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ring_len",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AioRingEntry, ring_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aio_ring_entry__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = nr_req */
  2,   /* field[2] = ring_len */
};
static const ProtobufCIntRange aio_ring_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor aio_ring_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aio_ring_entry",
  "AioRingEntry",
  "AioRingEntry",
  "",
  sizeof(AioRingEntry),
  3,
  aio_ring_entry__field_descriptors,
  aio_ring_entry__field_indices_by_name,
  1,  aio_ring_entry__number_ranges,
  (ProtobufCMessageInit) aio_ring_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mm_entry__field_descriptors[17] =
{
  {
    "mm_start_code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_start_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_end_code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_end_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_start_data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_start_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_end_data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_end_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_start_stack",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_start_stack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_start_brk",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_start_brk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_brk",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_brk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_arg_start",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_arg_start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_arg_end",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_arg_end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_env_start",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_env_start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_env_end",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MmEntry, mm_env_end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exe_file_id",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MmEntry, exe_file_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm_saved_auxv",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(MmEntry, n_mm_saved_auxv),
    offsetof(MmEntry, mm_saved_auxv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vmas",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MmEntry, n_vmas),
    offsetof(MmEntry, vmas),
    &vma_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dumpable",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(MmEntry, has_dumpable),
    offsetof(MmEntry, dumpable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aios",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MmEntry, n_aios),
    offsetof(MmEntry, aios),
    &aio_ring_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thp_disabled",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(MmEntry, has_thp_disabled),
    offsetof(MmEntry, thp_disabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mm_entry__field_indices_by_name[] = {
  15,   /* field[15] = aios */
  14,   /* field[14] = dumpable */
  11,   /* field[11] = exe_file_id */
  8,   /* field[8] = mm_arg_end */
  7,   /* field[7] = mm_arg_start */
  6,   /* field[6] = mm_brk */
  1,   /* field[1] = mm_end_code */
  3,   /* field[3] = mm_end_data */
  10,   /* field[10] = mm_env_end */
  9,   /* field[9] = mm_env_start */
  12,   /* field[12] = mm_saved_auxv */
  5,   /* field[5] = mm_start_brk */
  0,   /* field[0] = mm_start_code */
  2,   /* field[2] = mm_start_data */
  4,   /* field[4] = mm_start_stack */
  16,   /* field[16] = thp_disabled */
  13,   /* field[13] = vmas */
};
static const ProtobufCIntRange mm_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor mm_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mm_entry",
  "MmEntry",
  "MmEntry",
  "",
  sizeof(MmEntry),
  17,
  mm_entry__field_descriptors,
  mm_entry__field_indices_by_name,
  1,  mm_entry__number_ranges,
  (ProtobufCMessageInit) mm_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
