/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: netdev.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "netdev.pb-c.h"
void   net_device_entry__init
                     (NetDeviceEntry         *message)
{
  static NetDeviceEntry init_value = NET_DEVICE_ENTRY__INIT;
  *message = init_value;
}
size_t net_device_entry__get_packed_size
                     (const NetDeviceEntry *message)
{
  assert(message->base.descriptor == &net_device_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_device_entry__pack
                     (const NetDeviceEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_device_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_device_entry__pack_to_buffer
                     (const NetDeviceEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_device_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetDeviceEntry *
       net_device_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetDeviceEntry *)
     protobuf_c_message_unpack (&net_device_entry__descriptor,
                                allocator, len, data);
}
void   net_device_entry__free_unpacked
                     (NetDeviceEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &net_device_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netns_id__init
                     (NetnsId         *message)
{
  static NetnsId init_value = NETNS_ID__INIT;
  *message = init_value;
}
size_t netns_id__get_packed_size
                     (const NetnsId *message)
{
  assert(message->base.descriptor == &netns_id__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netns_id__pack
                     (const NetnsId *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netns_id__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netns_id__pack_to_buffer
                     (const NetnsId *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netns_id__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetnsId *
       netns_id__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetnsId *)
     protobuf_c_message_unpack (&netns_id__descriptor,
                                allocator, len, data);
}
void   netns_id__free_unpacked
                     (NetnsId *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &netns_id__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netns_entry__init
                     (NetnsEntry         *message)
{
  static NetnsEntry init_value = NETNS_ENTRY__INIT;
  *message = init_value;
}
size_t netns_entry__get_packed_size
                     (const NetnsEntry *message)
{
  assert(message->base.descriptor == &netns_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netns_entry__pack
                     (const NetnsEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netns_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netns_entry__pack_to_buffer
                     (const NetnsEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netns_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetnsEntry *
       netns_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetnsEntry *)
     protobuf_c_message_unpack (&netns_entry__descriptor,
                                allocator, len, data);
}
void   netns_entry__free_unpacked
                     (NetnsEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &netns_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor net_device_entry__field_descriptors[15] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NetDeviceEntry, type),
    &nd_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ifindex",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NetDeviceEntry, ifindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtu",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NetDeviceEntry, mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NetDeviceEntry, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetDeviceEntry, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tun",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NetDeviceEntry, tun),
    &tun_link_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(NetDeviceEntry, has_address),
    offsetof(NetDeviceEntry, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(NetDeviceEntry, n_conf),
    offsetof(NetDeviceEntry, conf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf4",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetDeviceEntry, n_conf4),
    offsetof(NetDeviceEntry, conf4),
    &sysctl_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf6",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetDeviceEntry, n_conf6),
    offsetof(NetDeviceEntry, conf6),
    &sysctl_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "macvlan",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NetDeviceEntry, macvlan),
    &macvlan_link_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_ifindex",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetDeviceEntry, has_peer_ifindex),
    offsetof(NetDeviceEntry, peer_ifindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_nsid",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetDeviceEntry, has_peer_nsid),
    offsetof(NetDeviceEntry, peer_nsid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "master",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NetDeviceEntry, has_master),
    offsetof(NetDeviceEntry, master),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sit",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NetDeviceEntry, sit),
    &sit_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_device_entry__field_indices_by_name[] = {
  6,   /* field[6] = address */
  7,   /* field[7] = conf */
  8,   /* field[8] = conf4 */
  9,   /* field[9] = conf6 */
  3,   /* field[3] = flags */
  1,   /* field[1] = ifindex */
  10,   /* field[10] = macvlan */
  13,   /* field[13] = master */
  2,   /* field[2] = mtu */
  4,   /* field[4] = name */
  11,   /* field[11] = peer_ifindex */
  12,   /* field[12] = peer_nsid */
  14,   /* field[14] = sit */
  5,   /* field[5] = tun */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange net_device_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor net_device_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "net_device_entry",
  "NetDeviceEntry",
  "NetDeviceEntry",
  "",
  sizeof(NetDeviceEntry),
  15,
  net_device_entry__field_descriptors,
  net_device_entry__field_indices_by_name,
  1,  net_device_entry__number_ranges,
  (ProtobufCMessageInit) net_device_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netns_id__field_descriptors[2] =
{
  {
    "target_ns_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NetnsId, target_ns_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "netnsid_value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NetnsId, netnsid_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netns_id__field_indices_by_name[] = {
  1,   /* field[1] = netnsid_value */
  0,   /* field[0] = target_ns_id */
};
static const ProtobufCIntRange netns_id__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor netns_id__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netns_id",
  "NetnsId",
  "NetnsId",
  "",
  sizeof(NetnsId),
  2,
  netns_id__field_descriptors,
  netns_id__field_indices_by_name,
  1,  netns_id__number_ranges,
  (ProtobufCMessageInit) netns_id__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netns_entry__field_descriptors[8] =
{
  {
    "def_conf",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(NetnsEntry, n_def_conf),
    offsetof(NetnsEntry, def_conf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all_conf",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(NetnsEntry, n_all_conf),
    offsetof(NetnsEntry, all_conf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "def_conf4",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetnsEntry, n_def_conf4),
    offsetof(NetnsEntry, def_conf4),
    &sysctl_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all_conf4",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetnsEntry, n_all_conf4),
    offsetof(NetnsEntry, all_conf4),
    &sysctl_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "def_conf6",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetnsEntry, n_def_conf6),
    offsetof(NetnsEntry, def_conf6),
    &sysctl_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all_conf6",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetnsEntry, n_all_conf6),
    offsetof(NetnsEntry, all_conf6),
    &sysctl_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nsids",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetnsEntry, n_nsids),
    offsetof(NetnsEntry, nsids),
    &netns_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext_key",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetnsEntry, ext_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netns_entry__field_indices_by_name[] = {
  1,   /* field[1] = all_conf */
  3,   /* field[3] = all_conf4 */
  5,   /* field[5] = all_conf6 */
  0,   /* field[0] = def_conf */
  2,   /* field[2] = def_conf4 */
  4,   /* field[4] = def_conf6 */
  7,   /* field[7] = ext_key */
  6,   /* field[6] = nsids */
};
static const ProtobufCIntRange netns_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor netns_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netns_entry",
  "NetnsEntry",
  "NetnsEntry",
  "",
  sizeof(NetnsEntry),
  8,
  netns_entry__field_descriptors,
  netns_entry__field_indices_by_name,
  1,  netns_entry__number_ranges,
  (ProtobufCMessageInit) netns_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue nd_type__enum_values_by_number[8] =
{
  { "LOOPBACK", "ND_TYPE__LOOPBACK", 1 },
  { "VETH", "ND_TYPE__VETH", 2 },
  { "TUN", "ND_TYPE__TUN", 3 },
  { "EXTLINK", "ND_TYPE__EXTLINK", 4 },
  { "VENET", "ND_TYPE__VENET", 5 },
  { "BRIDGE", "ND_TYPE__BRIDGE", 6 },
  { "MACVLAN", "ND_TYPE__MACVLAN", 7 },
  { "SIT", "ND_TYPE__SIT", 8 },
};
static const ProtobufCIntRange nd_type__value_ranges[] = {
{1, 0},{0, 8}
};
static const ProtobufCEnumValueIndex nd_type__enum_values_by_name[8] =
{
  { "BRIDGE", 5 },
  { "EXTLINK", 3 },
  { "LOOPBACK", 0 },
  { "MACVLAN", 6 },
  { "SIT", 7 },
  { "TUN", 2 },
  { "VENET", 4 },
  { "VETH", 1 },
};
const ProtobufCEnumDescriptor nd_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "nd_type",
  "nd_type",
  "NdType",
  "",
  8,
  nd_type__enum_values_by_number,
  8,
  nd_type__enum_values_by_name,
  1,
  nd_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
