/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pstree.proto */

#ifndef PROTOBUF_C_pstree_2eproto__INCLUDED
#define PROTOBUF_C_pstree_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PstreeEntry PstreeEntry;


/* --- enums --- */


/* --- messages --- */

struct  _PstreeEntry
{
  ProtobufCMessage base;
  uint32_t pid;
  uint32_t ppid;
  uint32_t pgid;
  uint32_t sid;
  size_t n_threads;
  uint32_t *threads;
};
#define PSTREE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pstree_entry__descriptor) \
    , 0, 0, 0, 0, 0,NULL }


/* PstreeEntry methods */
void   pstree_entry__init
                     (PstreeEntry         *message);
size_t pstree_entry__get_packed_size
                     (const PstreeEntry   *message);
size_t pstree_entry__pack
                     (const PstreeEntry   *message,
                      uint8_t             *out);
size_t pstree_entry__pack_to_buffer
                     (const PstreeEntry   *message,
                      ProtobufCBuffer     *buffer);
PstreeEntry *
       pstree_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pstree_entry__free_unpacked
                     (PstreeEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PstreeEntry_Closure)
                 (const PstreeEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pstree_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_pstree_2eproto__INCLUDED */
