/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: regfile.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "regfile.pb-c.h"
void   reg_file_entry__init
                     (RegFileEntry         *message)
{
  static RegFileEntry init_value = REG_FILE_ENTRY__INIT;
  *message = init_value;
}
size_t reg_file_entry__get_packed_size
                     (const RegFileEntry *message)
{
  assert(message->base.descriptor == &reg_file_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reg_file_entry__pack
                     (const RegFileEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reg_file_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reg_file_entry__pack_to_buffer
                     (const RegFileEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reg_file_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RegFileEntry *
       reg_file_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RegFileEntry *)
     protobuf_c_message_unpack (&reg_file_entry__descriptor,
                                allocator, len, data);
}
void   reg_file_entry__free_unpacked
                     (RegFileEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &reg_file_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const int32_t reg_file_entry__mnt_id__default_value = -1;
static const ProtobufCFieldDescriptor reg_file_entry__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RegFileEntry, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RegFileEntry, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RegFileEntry, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fown",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RegFileEntry, fown),
    &fown_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RegFileEntry, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mnt_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(RegFileEntry, has_mnt_id),
    offsetof(RegFileEntry, mnt_id),
    NULL,
    &reg_file_entry__mnt_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(RegFileEntry, has_size),
    offsetof(RegFileEntry, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RegFileEntry, has_ext),
    offsetof(RegFileEntry, ext),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RegFileEntry, has_mode),
    offsetof(RegFileEntry, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reg_file_entry__field_indices_by_name[] = {
  7,   /* field[7] = ext */
  1,   /* field[1] = flags */
  3,   /* field[3] = fown */
  0,   /* field[0] = id */
  5,   /* field[5] = mnt_id */
  8,   /* field[8] = mode */
  4,   /* field[4] = name */
  2,   /* field[2] = pos */
  6,   /* field[6] = size */
};
static const ProtobufCIntRange reg_file_entry__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor reg_file_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "reg_file_entry",
  "RegFileEntry",
  "RegFileEntry",
  "",
  sizeof(RegFileEntry),
  9,
  reg_file_entry__field_descriptors,
  reg_file_entry__field_indices_by_name,
  2,  reg_file_entry__number_ranges,
  (ProtobufCMessageInit) reg_file_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
