/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rlimit.proto */

#ifndef PROTOBUF_C_rlimit_2eproto__INCLUDED
#define PROTOBUF_C_rlimit_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _RlimitEntry RlimitEntry;


/* --- enums --- */


/* --- messages --- */

struct  _RlimitEntry
{
  ProtobufCMessage base;
  uint64_t cur;
  uint64_t max;
};
#define RLIMIT_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rlimit_entry__descriptor) \
    , 0, 0 }


/* RlimitEntry methods */
void   rlimit_entry__init
                     (RlimitEntry         *message);
size_t rlimit_entry__get_packed_size
                     (const RlimitEntry   *message);
size_t rlimit_entry__pack
                     (const RlimitEntry   *message,
                      uint8_t             *out);
size_t rlimit_entry__pack_to_buffer
                     (const RlimitEntry   *message,
                      ProtobufCBuffer     *buffer);
RlimitEntry *
       rlimit_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rlimit_entry__free_unpacked
                     (RlimitEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RlimitEntry_Closure)
                 (const RlimitEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rlimit_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_rlimit_2eproto__INCLUDED */
