/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rlimit.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rlimit.pb-c.h"
void   rlimit_entry__init
                     (RlimitEntry         *message)
{
  static RlimitEntry init_value = RLIMIT_ENTRY__INIT;
  *message = init_value;
}
size_t rlimit_entry__get_packed_size
                     (const RlimitEntry *message)
{
  assert(message->base.descriptor == &rlimit_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rlimit_entry__pack
                     (const RlimitEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rlimit_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rlimit_entry__pack_to_buffer
                     (const RlimitEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rlimit_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RlimitEntry *
       rlimit_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RlimitEntry *)
     protobuf_c_message_unpack (&rlimit_entry__descriptor,
                                allocator, len, data);
}
void   rlimit_entry__free_unpacked
                     (RlimitEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rlimit_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rlimit_entry__field_descriptors[2] =
{
  {
    "cur",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RlimitEntry, cur),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RlimitEntry, max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rlimit_entry__field_indices_by_name[] = {
  0,   /* field[0] = cur */
  1,   /* field[1] = max */
};
static const ProtobufCIntRange rlimit_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rlimit_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rlimit_entry",
  "RlimitEntry",
  "RlimitEntry",
  "",
  sizeof(RlimitEntry),
  2,
  rlimit_entry__field_descriptors,
  rlimit_entry__field_indices_by_name,
  1,  rlimit_entry__number_ranges,
  (ProtobufCMessageInit) rlimit_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
