/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sa.proto */

#ifndef PROTOBUF_C_sa_2eproto__INCLUDED
#define PROTOBUF_C_sa_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "opts.pb-c.h"

typedef struct _SaEntry SaEntry;


/* --- enums --- */


/* --- messages --- */

struct  _SaEntry
{
  ProtobufCMessage base;
  uint64_t sigaction;
  uint64_t flags;
  uint64_t restorer;
  uint64_t mask;
  protobuf_c_boolean has_compat_sigaction;
  protobuf_c_boolean compat_sigaction;
};
#define SA_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sa_entry__descriptor) \
    , 0, 0, 0, 0, 0,0 }


/* SaEntry methods */
void   sa_entry__init
                     (SaEntry         *message);
size_t sa_entry__get_packed_size
                     (const SaEntry   *message);
size_t sa_entry__pack
                     (const SaEntry   *message,
                      uint8_t             *out);
size_t sa_entry__pack_to_buffer
                     (const SaEntry   *message,
                      ProtobufCBuffer     *buffer);
SaEntry *
       sa_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sa_entry__free_unpacked
                     (SaEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SaEntry_Closure)
                 (const SaEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sa_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sa_2eproto__INCLUDED */
