/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sk-packet.proto */

#ifndef PROTOBUF_C_sk_2dpacket_2eproto__INCLUDED
#define PROTOBUF_C_sk_2dpacket_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ScmEntry ScmEntry;
typedef struct _SkPacketEntry SkPacketEntry;


/* --- enums --- */


/* --- messages --- */

struct  _ScmEntry
{
  ProtobufCMessage base;
  uint32_t type;
  size_t n_rights;
  uint32_t *rights;
};
#define SCM_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scm_entry__descriptor) \
    , 0, 0,NULL }


struct  _SkPacketEntry
{
  ProtobufCMessage base;
  uint32_t id_for;
  uint32_t length;
  /*
   * Reserved for message address
   * optional bytes		addr	= 3;
   */
  /*
   * Reserved for ucred restore
   * optional sk_ucred_entry	ucred	= 128;
   */
  size_t n_scm;
  ScmEntry **scm;
};
#define SK_PACKET_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sk_packet_entry__descriptor) \
    , 0, 0, 0,NULL }


/* ScmEntry methods */
void   scm_entry__init
                     (ScmEntry         *message);
size_t scm_entry__get_packed_size
                     (const ScmEntry   *message);
size_t scm_entry__pack
                     (const ScmEntry   *message,
                      uint8_t             *out);
size_t scm_entry__pack_to_buffer
                     (const ScmEntry   *message,
                      ProtobufCBuffer     *buffer);
ScmEntry *
       scm_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scm_entry__free_unpacked
                     (ScmEntry *message,
                      ProtobufCAllocator *allocator);
/* SkPacketEntry methods */
void   sk_packet_entry__init
                     (SkPacketEntry         *message);
size_t sk_packet_entry__get_packed_size
                     (const SkPacketEntry   *message);
size_t sk_packet_entry__pack
                     (const SkPacketEntry   *message,
                      uint8_t             *out);
size_t sk_packet_entry__pack_to_buffer
                     (const SkPacketEntry   *message,
                      ProtobufCBuffer     *buffer);
SkPacketEntry *
       sk_packet_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sk_packet_entry__free_unpacked
                     (SkPacketEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ScmEntry_Closure)
                 (const ScmEntry *message,
                  void *closure_data);
typedef void (*SkPacketEntry_Closure)
                 (const SkPacketEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor scm_entry__descriptor;
extern const ProtobufCMessageDescriptor sk_packet_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sk_2dpacket_2eproto__INCLUDED */
