/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sysctl.proto */

#ifndef PROTOBUF_C_sysctl_2eproto__INCLUDED
#define PROTOBUF_C_sysctl_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SysctlEntry SysctlEntry;


/* --- enums --- */

typedef enum _SysctlType {
  SYSCTL_TYPE__CTL_STR = 5,
  SYSCTL_TYPE__CTL_32 = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SYSCTL_TYPE)
} SysctlType;

/* --- messages --- */

struct  _SysctlEntry
{
  ProtobufCMessage base;
  SysctlType type;
  protobuf_c_boolean has_iarg;
  int32_t iarg;
  char *sarg;
};
#define SYSCTL_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sysctl_entry__descriptor) \
    , 0, 0,0, NULL }


/* SysctlEntry methods */
void   sysctl_entry__init
                     (SysctlEntry         *message);
size_t sysctl_entry__get_packed_size
                     (const SysctlEntry   *message);
size_t sysctl_entry__pack
                     (const SysctlEntry   *message,
                      uint8_t             *out);
size_t sysctl_entry__pack_to_buffer
                     (const SysctlEntry   *message,
                      ProtobufCBuffer     *buffer);
SysctlEntry *
       sysctl_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sysctl_entry__free_unpacked
                     (SysctlEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SysctlEntry_Closure)
                 (const SysctlEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    sysctl_type__descriptor;
extern const ProtobufCMessageDescriptor sysctl_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sysctl_2eproto__INCLUDED */
