/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: timer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "timer.pb-c.h"
void   itimer_entry__init
                     (ItimerEntry         *message)
{
  static ItimerEntry init_value = ITIMER_ENTRY__INIT;
  *message = init_value;
}
size_t itimer_entry__get_packed_size
                     (const ItimerEntry *message)
{
  assert(message->base.descriptor == &itimer_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t itimer_entry__pack
                     (const ItimerEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &itimer_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t itimer_entry__pack_to_buffer
                     (const ItimerEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &itimer_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ItimerEntry *
       itimer_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ItimerEntry *)
     protobuf_c_message_unpack (&itimer_entry__descriptor,
                                allocator, len, data);
}
void   itimer_entry__free_unpacked
                     (ItimerEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &itimer_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   posix_timer_entry__init
                     (PosixTimerEntry         *message)
{
  static PosixTimerEntry init_value = POSIX_TIMER_ENTRY__INIT;
  *message = init_value;
}
size_t posix_timer_entry__get_packed_size
                     (const PosixTimerEntry *message)
{
  assert(message->base.descriptor == &posix_timer_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t posix_timer_entry__pack
                     (const PosixTimerEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &posix_timer_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t posix_timer_entry__pack_to_buffer
                     (const PosixTimerEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &posix_timer_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PosixTimerEntry *
       posix_timer_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PosixTimerEntry *)
     protobuf_c_message_unpack (&posix_timer_entry__descriptor,
                                allocator, len, data);
}
void   posix_timer_entry__free_unpacked
                     (PosixTimerEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &posix_timer_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   task_timers_entry__init
                     (TaskTimersEntry         *message)
{
  static TaskTimersEntry init_value = TASK_TIMERS_ENTRY__INIT;
  *message = init_value;
}
size_t task_timers_entry__get_packed_size
                     (const TaskTimersEntry *message)
{
  assert(message->base.descriptor == &task_timers_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t task_timers_entry__pack
                     (const TaskTimersEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &task_timers_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t task_timers_entry__pack_to_buffer
                     (const TaskTimersEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &task_timers_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaskTimersEntry *
       task_timers_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaskTimersEntry *)
     protobuf_c_message_unpack (&task_timers_entry__descriptor,
                                allocator, len, data);
}
void   task_timers_entry__free_unpacked
                     (TaskTimersEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &task_timers_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor itimer_entry__field_descriptors[4] =
{
  {
    "isec",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ItimerEntry, isec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iusec",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ItimerEntry, iusec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vsec",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ItimerEntry, vsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vusec",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ItimerEntry, vusec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned itimer_entry__field_indices_by_name[] = {
  0,   /* field[0] = isec */
  1,   /* field[1] = iusec */
  2,   /* field[2] = vsec */
  3,   /* field[3] = vusec */
};
static const ProtobufCIntRange itimer_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor itimer_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "itimer_entry",
  "ItimerEntry",
  "ItimerEntry",
  "",
  sizeof(ItimerEntry),
  4,
  itimer_entry__field_descriptors,
  itimer_entry__field_indices_by_name,
  1,  itimer_entry__number_ranges,
  (ProtobufCMessageInit) itimer_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor posix_timer_entry__field_descriptors[10] =
{
  {
    "it_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, it_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clock_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, clock_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si_signo",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, si_signo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "it_sigev_notify",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, it_sigev_notify),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sival_ptr",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, sival_ptr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "overrun",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, overrun),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isec",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, isec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "insec",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, insec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vsec",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, vsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vnsec",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PosixTimerEntry, vnsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned posix_timer_entry__field_indices_by_name[] = {
  1,   /* field[1] = clock_id */
  7,   /* field[7] = insec */
  6,   /* field[6] = isec */
  0,   /* field[0] = it_id */
  3,   /* field[3] = it_sigev_notify */
  5,   /* field[5] = overrun */
  2,   /* field[2] = si_signo */
  4,   /* field[4] = sival_ptr */
  9,   /* field[9] = vnsec */
  8,   /* field[8] = vsec */
};
static const ProtobufCIntRange posix_timer_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor posix_timer_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "posix_timer_entry",
  "PosixTimerEntry",
  "PosixTimerEntry",
  "",
  sizeof(PosixTimerEntry),
  10,
  posix_timer_entry__field_descriptors,
  posix_timer_entry__field_indices_by_name,
  1,  posix_timer_entry__number_ranges,
  (ProtobufCMessageInit) posix_timer_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor task_timers_entry__field_descriptors[4] =
{
  {
    "real",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TaskTimersEntry, real),
    &itimer_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "virt",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TaskTimersEntry, virt),
    &itimer_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prof",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TaskTimersEntry, prof),
    &itimer_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "posix",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TaskTimersEntry, n_posix),
    offsetof(TaskTimersEntry, posix),
    &posix_timer_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned task_timers_entry__field_indices_by_name[] = {
  3,   /* field[3] = posix */
  2,   /* field[2] = prof */
  0,   /* field[0] = real */
  1,   /* field[1] = virt */
};
static const ProtobufCIntRange task_timers_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor task_timers_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "task_timers_entry",
  "TaskTimersEntry",
  "TaskTimersEntry",
  "",
  sizeof(TaskTimersEntry),
  4,
  task_timers_entry__field_descriptors,
  task_timers_entry__field_indices_by_name,
  1,  task_timers_entry__number_ranges,
  (ProtobufCMessageInit) task_timers_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
