/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: utsns.proto */

#ifndef PROTOBUF_C_utsns_2eproto__INCLUDED
#define PROTOBUF_C_utsns_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _UtsnsEntry UtsnsEntry;


/* --- enums --- */


/* --- messages --- */

struct  _UtsnsEntry
{
  ProtobufCMessage base;
  char *nodename;
  char *domainname;
};
#define UTSNS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&utsns_entry__descriptor) \
    , NULL, NULL }


/* UtsnsEntry methods */
void   utsns_entry__init
                     (UtsnsEntry         *message);
size_t utsns_entry__get_packed_size
                     (const UtsnsEntry   *message);
size_t utsns_entry__pack
                     (const UtsnsEntry   *message,
                      uint8_t             *out);
size_t utsns_entry__pack_to_buffer
                     (const UtsnsEntry   *message,
                      ProtobufCBuffer     *buffer);
UtsnsEntry *
       utsns_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   utsns_entry__free_unpacked
                     (UtsnsEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*UtsnsEntry_Closure)
                 (const UtsnsEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor utsns_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_utsns_2eproto__INCLUDED */
